### ISSUE TITLE
Jobs section 

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/spa-website-2022#103]

**Comment by asynchroza** [comment]
I've set the initial structure of the Jobs Section component. You may see what's getting rendered by it when you access the `/jobs` endpoint. Please, use the development branch called `#103-jobs-section`

**Comment by asynchroza** [comment]
[Example design](https://dribbble.com/shots/14145979-Job-Search-Platform)

**Comment by asynchroza** [comment]
How do I develop this: 
1. Request towards the api endpoint which retrieves all of the currently available jobs and on success -> change the state of the empty list called `jobsList`
```javascript
const [jobsList, setJobsList] = useState([])

useEffect(()=>{
axios.get(...)
.then((res)=>{
setJobsList(res.whatever)
})
}. [])
```

2. Map through the list and render components which are called job cards
```javascript
jobsList.map((job, index) => (
<JobCard props={job} key={index} />
))
```
3. Make sure everything is responsive :) -> probably use flexbox and have like three jobs on a row when viewed from a computer and display one job on a row when opened from a phone.
4. Refer to the currently implemented Carousels in `MembersSection`. They use the exact same way to map objects to components.

**Comment by asynchroza** [comment]
No filters should be added, just displaying the job as it's done in the example design

**Comment by SuelaCark** [comment]
@Aleks1908 @DemonHashira  --> Critical points to think about:
1. Do you want to keep the 'Part-time', 'Internship' tags? If so, keep in mind that we have to implement these also in the admin panel.
2. Be critical on responsiveness! Think about what happens if the logo is squared (1x1) or rectangular. The logo section should be able to hold any type of logo dimensions without destroying the job container.
